export const GET_CHARACTER_REQUEST = "GET_CHARACTER_REQUEST";
export const GET_CHARACTERS = "GET_CHARACTERS";
export const GET_CHARACTER_INFO = "GET_CHARACTER_INFO";
export const GET_CHARACTER_EPISODE = "GET_CHARACTER_EPISODE";
export const GET_CHARACTER_RESET = "GET_CHARACTER_RESET";
export const GET_CHARACTER_EPISODE_RESET = "GET_CHARACTER_EPISODE_RESET";
export const GET_CHARACTER_ERROR = "GET_CHARACTER_ERROR";
